call pathogen#incubate()
call pathogen#helptags()
set nocompatible
set encoding=utf8
set paste
set textwidth=0
set tabstop=4
set softtabstop=4
set autoindent
set backspace=indent,eol,start
set ruler
set wildmenu
syntax on
set nu
set dictionary+=/usr/share/dict/words
set smartcase
set mouse=a
set shiftround
set title
set wildmenu
colors elflord
set ic
set ruler
